[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python3 -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt"]

[variables]
PATH = "/opt/venv/bin:$PATH"

[start]
cmd = "/opt/venv/bin/python server.py"
